// Test generated by RoostGPT for test demo using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Person_getLastName_de1cc748dc_Test {

    private Person person;

    @BeforeEach
    public void setUp() {
        this.person = new Person();
    }

    @Test
    public void testGetLastName() {
        String expectedLastName = "Smith";
        this.person.setLastName(expectedLastName);
        String actualLastName = this.person.getLastName();
        assertEquals(expectedLastName, actualLastName, "The last name should be Smith");
    }

    @Test
    public void testGetLastNameWhenLastNameIsNull() {
        this.person.setLastName(null);
        String actualLastName = this.person.getLastName();
        assertEquals(null, actualLastName, "The last name should be null");
    }
}
